### ISSUE TITLE
To slooooow...

### ISSUE THREAD

**Issue by wzykubek** [M3NIX/rofi-keepass#1]
Hi, your script opens a database of ~5 seconds!!! This is terrible. I made own script written in shell script (zsh) which is faster than it. If you want you can use my script or you should make your script faster but is it difficult when you write it in python.
[Link to my script repo](https://github.com/samedamci/rofi-keepassxc)
But nevertheless it is very cool script. :dancing_women:

**Comment by M3NIX** [comment]
Thank you for your feedback.
I will see what I can do :relaxed:
